# Load necessary libraries for data manipulation, modeling, and visualization
library(tidyverse)
library(tidymodels)
library(vip)
library(readxl)
library(parallel)
library(doParallel)
library(gtable)
library(cowplot)
library(patchwork)
library(rules)
library(baguette)
library(RColorBrewer)
library(ranger)
library(xgboost)
library(earth)
library(Cubist)
library(kernlab)
library(kknn)
library(finetune)
library(lme4)
library(ggrepel)
library(yardstick)
library(caret)
library(stacks)
library(ggtext)
library(embed)
library(colino)
library(Boruta)
library(dbarts)
library(randomForest) # Needed only if RF_library = "randomForest"

tidymodels_prefer()